FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy pip.conf for faster mirrors
COPY pip.conf /etc/pip.conf

# Copy only the requirements file to leverage Docker cache
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Define environment variable
ENV FLASK_APP app.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=8501"]